### ISSUE TITLE
Recrafted support

### ISSUE THREAD

**Issue by tomodachi94** [unicornpkg/unicornpkg#12]
Add support for the [Recrafted custom BIOS](https://github.com/Ocawesome101/recrafted). We would be the first package manager to have support for it.

Should be a trivial if-block at the start of `core.lua` that `require`s Recrafted libraries.

**Comment by Apethesis** [comment]
now i need to make a package manager with support for everything

**Comment by tomodachi94** [comment]
@Apethesis just use Unicornpkg, we just added remotes to the API, and the CLI is going to ship soon. (Read: `apt-get`-style package installation.)

**Comment by Apethesis** [comment]
but i like pacman

**Comment by tomodachi94** [comment]
Pacman-like features are going to come to Unicornpkg soon. Stay tuned!

(PS: Most CLI-related work occurs in [unicornpkg/cli](https://github.com/unicornpkg/cli).)

**Comment by tomodachi94** [comment]
@Apethesis Pacman-like interface is done. See the [installation instructions](https://unicornpkg.madefor.cc/how-tos/installation.html) for more information.
